/**
 * 
 */
package domain.service.highcharts.utils;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

/**
 * @author 99GU3997
 */
public class CodigosISOWorldCountries {

	public static final Map<String, String> isoWorldCodes = new HashMap<String, String>();
	static {
		isoWorldCodes.put("dz", "");
		isoWorldCodes.put("ao", "");
		isoWorldCodes.put("eg", "");
		isoWorldCodes.put("bd", "");
		isoWorldCodes.put("ne", "");
		isoWorldCodes.put("qa", "");
		isoWorldCodes.put("na", "");
		isoWorldCodes.put("bg", "");
		isoWorldCodes.put("bo", "");
		isoWorldCodes.put("gh", "");
		isoWorldCodes.put("pk", "");
		isoWorldCodes.put("pa", "");
		isoWorldCodes.put("jo", "");
		isoWorldCodes.put("eh", "");
		isoWorldCodes.put("ly", "");
		isoWorldCodes.put("my", "");
		isoWorldCodes.put("pr", "");
		isoWorldCodes.put("kp", "");
		isoWorldCodes.put("tz", "");
		isoWorldCodes.put("pt", "");
		isoWorldCodes.put("kh", "");
		isoWorldCodes.put("py", "");
		isoWorldCodes.put("sa", "");
		isoWorldCodes.put("me", "");
		isoWorldCodes.put("si", "");
		isoWorldCodes.put("bf", "");
		isoWorldCodes.put("kh", "");
		isoWorldCodes.put("py", "");
		isoWorldCodes.put("sa", "");
		isoWorldCodes.put("me", "");
		isoWorldCodes.put("si", "");
		isoWorldCodes.put("bf", "");
		isoWorldCodes.put("ch", "");//26
        isoWorldCodes.put("mr", "");//27
        isoWorldCodes.put("hr", "");//28
        isoWorldCodes.put("cl", "");//29
        isoWorldCodes.put("cn", "");//30
        isoWorldCodes.put("kn", "");//31
        isoWorldCodes.put("jm", "");//32
        isoWorldCodes.put("dj", "");//33
        isoWorldCodes.put("gn", "");//34
        isoWorldCodes.put("fi", "");//35
        isoWorldCodes.put("uy", "");//36
        isoWorldCodes.put("va", "");//37
        isoWorldCodes.put("np", "");//38
        isoWorldCodes.put("ma", "");//39
        isoWorldCodes.put("ye", "");//40
        isoWorldCodes.put("ph", "");//41
        isoWorldCodes.put("za", "");//42
        isoWorldCodes.put("ni", "");//43
        isoWorldCodes.put("cyn", "");//44
        isoWorldCodes.put("vi", "");//45
        isoWorldCodes.put("sy", "");//46
        isoWorldCodes.put("li", "");//47
        isoWorldCodes.put("mt", "");//48
        isoWorldCodes.put("kz", "");//49
        isoWorldCodes.put("mn", "");//50
        isoWorldCodes.put("sr", "");//51
        isoWorldCodes.put("ie", "");//52
        isoWorldCodes.put("dm", "");//53
        isoWorldCodes.put("bj", "");//54
        isoWorldCodes.put("ng", "");//55
        isoWorldCodes.put("be", "");//56
        isoWorldCodes.put("tg", "");//57
        isoWorldCodes.put("de", "");//58
        isoWorldCodes.put("lk", "");//59
        isoWorldCodes.put("gb", "");//60
        isoWorldCodes.put("gy", "");//61
        isoWorldCodes.put("cr", "");//62
        isoWorldCodes.put("cm", "");//63
        isoWorldCodes.put("kas", "");//64
        isoWorldCodes.put("km", "");//65
        isoWorldCodes.put("ug", "");//66
        isoWorldCodes.put("tm", "");//67
        isoWorldCodes.put("tt", "");//68
        isoWorldCodes.put("nl", "");//69
        isoWorldCodes.put("td", "");//70
        isoWorldCodes.put("ge", "");//71
        isoWorldCodes.put("ro", "");//72
        isoWorldCodes.put("scr", "");//73
        isoWorldCodes.put("lv", "");//74
        isoWorldCodes.put("bz", "");//75
        isoWorldCodes.put("mm", "");//76
        isoWorldCodes.put("af", "");//77
        isoWorldCodes.put("bi", "");//78
        isoWorldCodes.put("by", "");//79
        isoWorldCodes.put("gd", "");//80
        isoWorldCodes.put("lr", "");//81
        isoWorldCodes.put("gr", "");//82
        isoWorldCodes.put("ls", "");//83
        isoWorldCodes.put("gl", "");//84
        isoWorldCodes.put("ad", "");//85
        isoWorldCodes.put("mz", "");//86
        isoWorldCodes.put("tj", "");//87
        isoWorldCodes.put("th", "");//88
        isoWorldCodes.put("ht", "");//89
        isoWorldCodes.put("mx", "");//90
        isoWorldCodes.put("zw", "");//91
        isoWorldCodes.put("lc", "");//92
        isoWorldCodes.put("in", "");//93
        isoWorldCodes.put("vc", "");//94
        isoWorldCodes.put("bt", "");//95
        isoWorldCodes.put("vn", "");//96
        isoWorldCodes.put("no", "");//97
        isoWorldCodes.put("cz", "");//98
        isoWorldCodes.put("ag", "");//99
        isoWorldCodes.put("fj", "");//100
        isoWorldCodes.put("hn", "");//101
        isoWorldCodes.put("mu", "");//102
        isoWorldCodes.put("do", "");//103
        isoWorldCodes.put("lu", "");//104
        isoWorldCodes.put("il", "");//105
        isoWorldCodes.put("sm", "");//106
        isoWorldCodes.put("pe", "");//107
        isoWorldCodes.put("id", "");//108
        isoWorldCodes.put("vu", "");//109
        isoWorldCodes.put("mk", "");//110
        isoWorldCodes.put("cd", "");//111
        isoWorldCodes.put("cg", "");//112
        isoWorldCodes.put("is", "");//113
        isoWorldCodes.put("et", "");//114
        isoWorldCodes.put("um", "");//115
        isoWorldCodes.put("co", "");//116
        isoWorldCodes.put("ser", "");//117
        isoWorldCodes.put("bw", "");//118
        isoWorldCodes.put("md", "");//119
        isoWorldCodes.put("mg", "");//120
        isoWorldCodes.put("ec", "");//121
        isoWorldCodes.put("sn", "");//122
        isoWorldCodes.put("tl", "");//123
        isoWorldCodes.put("fr", "");//124
        isoWorldCodes.put("lt", "");//125
        isoWorldCodes.put("rw", "");//126
        isoWorldCodes.put("zm", "");//127
        isoWorldCodes.put("gm", "");//128
        isoWorldCodes.put("fo", "");//129
        isoWorldCodes.put("gt", "");//130
        isoWorldCodes.put("dk", "");//131
        isoWorldCodes.put("ua", "");//132
        isoWorldCodes.put("au", "");//133
        isoWorldCodes.put("at", "");//134
        isoWorldCodes.put("ve", "");//135
        isoWorldCodes.put("pw", "");//136
        isoWorldCodes.put("ke", "");//137
        isoWorldCodes.put("la", "");//138
        isoWorldCodes.put("bjn", "");//139
        isoWorldCodes.put("tr", "");//140
        isoWorldCodes.put("jp", "");//141
        isoWorldCodes.put("al", "");//142
        isoWorldCodes.put("om", "");//143
        isoWorldCodes.put("it", "");//144
        isoWorldCodes.put("bn", "");//145
        isoWorldCodes.put("tn", "");//146
        isoWorldCodes.put("hu", "");//147
        isoWorldCodes.put("ru", "");//148
        isoWorldCodes.put("lb", "");//149
        isoWorldCodes.put("bb", "");//150
        isoWorldCodes.put("br", "");//151
        isoWorldCodes.put("ci", "");//152
        isoWorldCodes.put("rs", "");//153
        isoWorldCodes.put("gq", "");//154
        isoWorldCodes.put("us", "");//155
        isoWorldCodes.put("se", "");//156
        isoWorldCodes.put("az", "");//157
        isoWorldCodes.put("gw", "");//158
        isoWorldCodes.put("sz", "");//159
        isoWorldCodes.put("ca", "");//160
        isoWorldCodes.put("kv", "");//161
        isoWorldCodes.put("kr", "");//162
        isoWorldCodes.put("mw", "");//163
        isoWorldCodes.put("sk", "");//164
        isoWorldCodes.put("cy", "");//165
        isoWorldCodes.put("ba", "");//166
        isoWorldCodes.put("pga", "");//167
        isoWorldCodes.put("sg", "");//168
        isoWorldCodes.put("tw", "");//169
        isoWorldCodes.put("so", "");//170
        isoWorldCodes.put("sol", "");//171
        isoWorldCodes.put("uz", "");//172
        isoWorldCodes.put("cf", "");//173
        isoWorldCodes.put("pl", "");//174
        isoWorldCodes.put("kw", "");//175
        isoWorldCodes.put("er", "");//176
        isoWorldCodes.put("ga", "");//177
        isoWorldCodes.put("ee", "");//178
        isoWorldCodes.put("es", "");//179
        isoWorldCodes.put("iq", "");//180
        isoWorldCodes.put("sv", "");//181
        isoWorldCodes.put("ml", "");//182
        isoWorldCodes.put("st", "");//183
        isoWorldCodes.put("ir", "");//184
        isoWorldCodes.put("sl", "");//185
        isoWorldCodes.put("cnm", "");//186
        isoWorldCodes.put("bs", "");//187
        isoWorldCodes.put("sb", "");//188
        isoWorldCodes.put("nz", "");//189
        isoWorldCodes.put("mc", "");//190
        isoWorldCodes.put("ss", "");//191
        isoWorldCodes.put("kg", "");//192
        isoWorldCodes.put("ae", "");//193
        isoWorldCodes.put("ar", "");//194
        isoWorldCodes.put("sd", "");//195
        isoWorldCodes.put("bh", "");//196
        isoWorldCodes.put("am", "");//197
        isoWorldCodes.put("pg", "");//198
        isoWorldCodes.put("cu", "");//199
        
        Iterator<String> iteKeys = isoWorldCodes.keySet().iterator();
        while (iteKeys.hasNext()) {
        	String key = iteKeys.next();
        	isoWorldCodes.put(key,  key);
        }
		
     }

}
